/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ProductAttributeCreateNestedManyWithoutProductsInput } from "./ProductAttributeCreateNestedManyWithoutProductsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsNumber,
} from "class-validator";
import { Type } from "class-transformer";
import { BrandWhereUniqueInput } from "../../brand/base/BrandWhereUniqueInput";
import { CategoryCreateNestedManyWithoutProductsInput } from "./CategoryCreateNestedManyWithoutProductsInput";
import { OrderWhereUniqueInput } from "../../order/base/OrderWhereUniqueInput";
@InputType()
class ProductCreateInput {
  @ApiProperty({
    required: false,
    type: () => ProductAttributeCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ProductAttributeCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ProductAttributeCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  attributes?: ProductAttributeCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: true,
    type: () => BrandWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => BrandWhereUniqueInput)
  @Field(() => BrandWhereUniqueInput)
  brand!: BrandWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => CategoryCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => CategoryCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => CategoryCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  categories?: CategoryCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => OrderWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OrderWhereUniqueInput)
  @IsOptional()
  @Field(() => OrderWhereUniqueInput, {
    nullable: true,
  })
  order?: OrderWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  price!: number;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  sku!: string;
}
export { ProductCreateInput };
